
CREATE OR REPLACE TABLE TBAE_USER(
	USER_ID			INTEGER 	NOT NULL AUTO_INCREMENT,
	USER_NAME		VARCHAR(64)	NOT NULL,
	USER_PASSWORD	VARCHAR(64)	NOT NULL,
	
	PRIMARY KEY(USER_ID)
);


CREATE OR REPLACE TABLE TBAE_ROLE(
	ROLE_ID			INTEGER 	NOT NULL AUTO_INCREMENT,
	ROLE_NAME		VARCHAR(64)	NOT NULL,
	
	PRIMARY KEY(ROLE_ID)
);



CREATE OR REPLACE TABLE TBAE_USER_ROLE(
	USER_ROLE_ID	INTEGER		NOT NULL AUTO_INCREMENT,
	ROLE_ID			INTEGER		NOT NULL,
	USER_ID			INTEGER 	NOT NULL,
	
	PRIMARY KEY(USER_ROLE_ID)
);


CREATE OR REPLACE TABLE TBAE_PROFILE(
	PROFILE_ID				INTEGER 	NOT NULL AUTO_INCREMENT,
	USER_ID					INTEGER		NOT NULL,
	GENDER					FLOAT		NOT NULL,
	NON_BINARY_GENDER		BOOLEAN		DEFAULT (false),
	NON_BINARY_GENDER_ID	INTEGER		NOT NULL
		
	PRIMARY KEY	(PROFILE_ID)
);

CREATE OR REPLACE TABLE TBAE_NON_BINARY_GENDER(
	NON_BINARY_GENDER_ID	INTEGER		NOT NULL AUTO_INCREMENT,
	GENDER_DESCRIPTION		VARCHAR(64) NOT NULL,
	
	PRIMARY KEY(NON_BINARY_GENDER_ID)
);