INSERT INTO TBAE_USER (USER_ID, USER_NAME, USER_PASSWORD) VALUE(1,"User1","Password1");


INSERT INTO TBAE_ROLE (ROLE_ID, ROLE_NAME) VALUE(1,"Default Role");


INSERT INTO TBAE_USER_ROLE (USER_ROLE_ID, USER_ID, ROLE_ID) VALUES(1,1,1);