DROP VIEW IF EXISTS VBAE_USER_ROLES;
CREATE OR REPLACE VIEW VBAE_USER_ROLE_LIST AS SELECT
	u.USER_ID,
	r.ROLE_ID,
	u.USER_NAME,
	r.ROLE_NAME
FROM TBAE_USER_ROLE as s
JOIN TBAE_USER u ON s.USER_ID = u.USER_ID 
JOIN TBAE_ROLE r ON s.ROLE_ID = r.ROLE_ID 
;